version: 2
jobs:
  build_test_deploy:
    machine: true
    environment:
      USER_NAME: circleci
      USER_UID: 1001
      USER_GID: 1001
      TZ: Europe/Berlin
    steps:
      - checkout
      - run:
          name: Build webknossos-dev docker image
          command: |
            docker pull scalableminds/webknossos-dev:$CIRCLE_BRANCH || true
            DEV_CACHE=$CIRCLE_BRANCH docker-compose build base
      - run:
          name: Prepare dependency folders
          command: mkdir -p project/target target ~/.m2 ~/.ivy2 ~/.sbt ~/.yarn-cache
      - restore_cache:
          keys:
            - cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}
            - cache-{{ checksum ".circleci/cache_version" }}-master
      - restore_cache:
          keys:
            - node_modules-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install frontend dependencies
          command: docker-compose run base yarn install --frozen-lockfile

      - save_cache:
          key: cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - "project/target"
            - "target"
            - "~/.m2"
            - "~/.ivy2"
            - "~/.sbt"
            - "~/.yarn-cache"

      - save_cache:
        key: node_modules-cache-{{ checksum "yarn.lock" }}
        paths:
          - "node_modules"
workflows:
  version: 2
  default:
    jobs:
      - build_test_deploy:
          filters:
            tags:
              only: /.*/
